### PR TITLE
Add auto eject option

### LINKED ISSUE #190: Request: optionally eject disc as soon as read phase is complete
Hi,

Could an option be added to redumper to eject the disc as soon as the SCSI interaction is completed, please - before Hash values, Info and Skeleton are attempted.  BD discs can take a long time for the (especially) Skeleton phase to complete and all the while the drive is unused.  I use the CLI version under Linux and I feel it would be efficient for me to be able to know I can change disc and start a new dump while the final phases of the previous disc are still completing.

Thanks for your consideration.

### PR DESCRIPTION
**Pull request by Deterous**
This adds an auto eject option (`--auto-eject`) that will eject the disc once all the phases that use the disc are complete.
i.e. it will eject the disc after rings/dump/refine/verify/dvdkey is done, but redumper will continue with protection/split/hash/info/skeleton phases.

It ejects the disc by calling the scsi START_STOP_UNIT (0x1B) command which I have added to `scsi/cmd.ixx` and `scsi/mmc.ixx`

Fixes #190 and also fixes an issue with LG/ASUS (so-called UHD friendly drives) that have the sleep bug (the disc/drive makes terrible noises after a BDXL disc like PS5 & 4K-BD have been in the drive idle for a minute or two, which can happen during skeleton phase).

Also sorry for the many commits, best to squash merge.

### CODE REVIEW

**Comment by superg** [comment]
I would rather have that implemented as "eject" command.

**Comment by Deterous** [comment]
> I would rather have that implemented as "eject" command.

I can refactor it to be a command, but would the logic for looking ahead to see if future commands use the drive remain, with `--auto-eject`?
Or would you create new alias for `cd`, `dvd`, etc that insert an eject command after refine?

**Comment by superg** [comment]
> I can refactor it to be a command, but would the logic for looking ahead to see if future commands use the drive remain, with `--auto-eject`? Or would you create new alias for `cd`, `dvd`, etc that insert an eject command after refine?

I am just thinking about the swap disc usecase (for the drives that allow it), it would be useful to have it as a separate command. 
We can still have an `--auto-eject` option that will insert eject into the appropriate spot in the batch command lists.

Change the interface
`std::list<std::string> get_cd_batch_commands(Context &ctx, const std::string &command)`
to
`std::list<std::string> get_cd_batch_commands(Context &ctx, const std::string &command, bool eject)`

In `get_cd_batch_commands`, for cd it has to come after refine/refinenew, for dvd after dvdkey and for the other profiles after refine.

and in redumper.ixx call it like:
`auto cd_batch_commands = get_cd_batch_commands(ctx, c, options.auto_eject);`

**Comment by Deterous** [comment]
Alright, I think that's what you meant, made an eject command and created new batch commands depending on if auto eject option was enabled.

**Review by superg — APPROVED** [review]
Overall looks good!
(I'll refactor get_cd_batch_commands() later, I think it can be cleaner)

**Pull request merged**
