### PR TITLE
fix: `read_physical_structures` failing for multi-layer BDs.

### PR DESCRIPTION
**Pull request by Didrole**
Proposal fix for issue #174

### CODE REVIEW

**Comment by Didrole** [comment]
I understand that the diff is a bit messy looking and I gave no explanation.  
I basically moved all the BD specific logic out of the `layers_count` loop to clearly differentiate BD logic from DVD logic.  

A simple break statement may be another solution (by IMO less readable).

**Comment by superg** [comment]
Let me get back to my PC tonight and I will review everything again. Just want to make sure I don't introduce any regressions while I took a break from active redumper development.

**Comment by Deterous** [comment]
I have tested this and confirmed it also fixes #153

**Comment by superg** [comment]
Ok, I pulled it locally and this is very good. I agree that it makes sense to have logic split between bluray and dvd even if there is some code duplication.

**Comment by JohnVeness** [comment]
Many thanks for working together on this - I can now dump Xbox One games (which are almost all 2 layer) which were previously failing.

**Pull request merged**
