### PR TITLE
Add fallback for CD-R detection

### PR DESCRIPTION
**Pull request by HeroponRikiBestest**
Some drives don't properly return whether media is recordable with the current configuration check. This pull request adds a fallback after the mediatype is determined, checking if the media is of type CD-ROM, and if it is, checking for the presence of an ATIP, setting mediatype to CD-R if it is.

### CODE REVIEW

**Comment by HeroponRikiBestest** [comment]
I have a CD-R that redumper recognizes as being a CD-ROM on my JB8 ASUS drive, but recognizes as a CD-R on my PX-4824. 

[iambicASUS.zip](https://github.com/user-attachments/files/16073194/iambicASUS.zip)
[iambic.log](https://github.com/user-attachments/files/16073199/iambic.log)
`current profile: CD-ROM`


[iambicPLEX.zip](https://github.com/user-attachments/files/16073204/iambicPLEX.zip)
[iambic.log](https://github.com/user-attachments/files/16073210/iambic.log)
`current profile: CD-R`

With this change, redumper identifies it as a CD-R on my ASUS drive too. I apologize if this change is not desired; while I noticed that it was a CD-R when I went to read the ringcodes, I usually rely on redumper's log output to determine if a disc is a CD-R, as that info needs to go in the comments when submitting to redump. If it is desired, and there is anything I can do to better implement it, please let me know.

**Comment by superg** [comment]
Ok, so this doesn't affect any functional behavior, just the console output.
I am fixing some profile misdetection for BD-R, but I am using layer descriptor information where it clearly says BDR, the check like this is great. But CD lacks such definitive descriptors.
I don't think that ATIP check is suitable here, what if some pressed discs will return ATIP?

I suggest to look at the disc using eyes if you aren't sure if it's pressed or not. Funny, I know :)

**Comment by HeroponRikiBestest** [comment]
I thought it was safe to add because [Aaru](https://github.com/aaru-dps/Aaru/blob/ae8d6e385459c0607a137693eca96eb397f89598/Aaru.Core/Media/Info/ScsiInfo.cs#L1339l) and other sources say that pressed discs can't have ATIP.

I apologize, but please don't make fun of me; I already check the physical disc, I just wanted to see if I could fix the check.

**Comment by superg** [comment]
PMA and ATIP are somewhere in the leadin. True that specs say that it shouldn't exist on pressed CD's but I don't think anything prevents you from structuring the disc the way it's there even on pressed media. 
Also, there are bootleg discs that were mastered from CD-R like media (2 C2 errors in the end) and I have plenty of them, there is a chance that there might be other CD-R properties there, that's why I am cautious.

**Comment by superg** [comment]
--disc-type option is added

**Pull request closed without merging**
